services:
  terraria:
    build:
      context: .
      dockerfile: Dockerfile
    image: terraria-server:local
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
    volumes:
      - ./data:/config
    environment:
      PORT: "7777"
      MAX_PLAYERS: "8"
      TZ: "UTC"
      #WORLD: "MyWorld.wld"
    tty: true        # docker run -t
    stdin_open: true # docker run -i
    restart: unless-stopped